### PR TITLE
Modular update

### PR DESCRIPTION
**Pull request by acramernc**

### CODE REVIEW

**Comment by KittenMoon** [comment]
nw forgs

**Comment by acramernc** [comment]
@Aconka make this happen

**Comment by KittenMoon** [comment]
Added speed, productivity, and efficiency modules ... wait this isnt factorio chat

**Comment by galvanized** [comment]
lgtm
(i didn't look at it)

**Comment by KittenMoon** [comment]
ඞ

**Comment by acramernc** [comment]
Added helperFuncs.js to contain additional functions outside of chat processing, converted to node module and updated imports to match

**Comment by acramernc** [comment]
also fixed all the places where sami didn't initialize variables

**Comment by acramernc** [comment]
wrong branch

**Pull request closed without merging**
